
access_key ="on_bYfDyZ0QtxjnQOAqlSPTD"
secret_key="aeSrt2XWfSFFTxOwiUMtHKnpaNNQfBrqAnekcX7VgSqeo2xL"
openai_api_key="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"
 

from typing import TypedDict, Annotated, Sequence, List, Literal, Optional
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
from langchain_core.messages import BaseMessage, SystemMessage, HumanMessage, AIMessage

OPENAI_HARDCODED_KEY = openai_api_key



class AgentState(TypedDict):
    messages: Sequence[BaseMessage]
    doc_id: str
    work_id: str
    elem_id: str
    available_tools: List[dict]
    next_action: Optional[dict]       # Stores the tool call description while waiting for user approval
    approval_granted: Optional[bool]  # True/False response from the frontend
    final_reply: Optional[str]

def core_agent_node(state: AgentState):
    """The model reads the user request and selects the optimal MCP tool action."""
    llm = ChatOpenAI(model="gpt-4o", temperature=0, api_key=OPENAI_HARDCODED_KEY)
    
    # Format the tools so the LLM knows how to declare parameters
    tools_summary = "\n".join([
        f"- Name: {t.name}, Description: {t.description}, Schema: {t.inputSchema}"
        for t in state['available_tools']
    ])
    
    system_msg = SystemMessage(
        "You are an elite autonomous Onshape CAD agent acting as an MCP orchestration manager.\n"
        "Analyze the user's geometric modeling request and choose the next tool action from the available list below.\n\n"
        "--- AVAILABLE MCP TOOLS ---\n"
        f"{tools_summary}\n\n"
        "--- RESPONSE MANDATE ---\n"
        "If you need to execute an action, return a clean JSON payload specifying the target tool name and parameter arguments:\n"
        "```json\n"
        "{\"action\": \"CALL_TOOL\", \"name\": \"tool_name\", \"arguments\": {...}}\n"
        "```\n"
        "If the objective is reached, print your final confirmation summary clearly."
    )
    
    response = llm.invoke([system_msg] + list(state['messages']))
    content = response.content
    
    # Parse out structured tool calls if generated by the model
    if "```json" in content:
        try:
            clean_json = content.split("```json")[1].split("```")[0].strip()
            action_data = json.loads(clean_json)
            return {"next_action": action_data, "messages": [response]}
        except:
            pass
            
    return {"final_reply": content, "messages": [response]}

def create_graph():
    workflow = StateGraph(AgentState)
    workflow.add_node("agent", core_agent_node)
    workflow.add_edge(START, "agent")
    workflow.add_edge("agent", END)
    return workflow.compile()