import os
import requests
from django.http import JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt
from .agent import run_cad_agent  # <--- Import our new LangGraph runner



def onshape_callback(request):
    # 1. Catch the unique authorization code sent by Onshape
    auth_code = request.GET.get('code')
    
    if not auth_code:
        return JsonResponse({'status': 'error', 'message': 'No authorization code detected.'}, status=400)
    
    # 2. Fetch and sanitize environment keys (strip trailing whitespaces/newlines)
    client_id = os.environ.get('ONSHAPE_CLIENT_ID', '').strip()
    client_secret = os.environ.get('ONSHAPE_CLIENT_SECRET', '').strip()
    
    # 💥 DEBUG PRINT: Check Render's log console to ensure these print lengths > 0
    print(f"[DEBUG] Extracted Client ID Length: {len(client_id)}")
    print(f"[DEBUG] Extracted Client Secret Length: {len(client_secret)}")
    
    # 3. Reconstruct the dynamic redirect_uri exactly as requested by the browser
    # This prevents byte-for-byte string mismatches automatically
    actual_redirect_uri = request.build_absolute_uri(request.path)
    print(f"[DEBUG] Matching Redirect URI used: {actual_redirect_uri}")

    # 4. Prepare the explicit exchange payload
    token_url = "https://oauth.onshape.com/oauth/token"
    payload = {
        'grant_type': 'authorization_code',
        'code': auth_code,
        'client_id': client_id,
        'client_secret': client_secret,
        'redirect_uri': actual_redirect_uri,
    }
    
    # Enforce standard form encoding headers
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Accept': 'application/json'
    }
    
    # 5. Outbound request execution
    response = requests.post(token_url, data=payload, headers=headers)
    
    print(f"[DEBUG] Onshape Token Endpoint Response Status: {response.status_code}")
    print(f"[DEBUG] Onshape Token Endpoint Body: {response.text}")
    
    if response.status_code == 200:
        tokens = response.json()
        return JsonResponse({
            'status': 'success', 
            'message': 'Authenticated with Onshape successfully!',
            'access_token_preview': tokens.get('access_token')[:10] + "..."
        })
    else:
        # Return Onshape's error parameters directly to the window for triage
        return JsonResponse({
            'status': 'handshake_failed',
            'onshape_error_payload': response.json(),
            'attempted_payload_meta': {
                'client_id_filled': bool(client_id),
                'client_secret_filled': bool(client_secret),
                'redirect_uri_used': actual_redirect_uri
            }
        }, status=response.status_code)
    


import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .agent import create_graph, HumanMessage  # Ensure graph elements are accessible

@csrf_exempt
def api_chat(request):
    if request.method != 'POST':
        return JsonResponse({'error': 'Only POST requests allowed'}, status=405)
    
    try:
        data = json.loads(request.body)
        user_prompt = data.get('prompt', '')
        cad_context = data.get('context', {})
        selected_entity = data.get('selectedEntity')
        
        doc_id = cad_context.get('documentId')
        work_id = cad_context.get('workspaceId')
        elem_id = cad_context.get('elementId')
        
        print(f"[LANGGRAPH INGEST] Compiling execution traces for prompt: {user_prompt}")
        
        # 🕸️ Instantiate the multi-agent graph network layout
        graph = create_graph()
        initial_state = {
            "messages": [HumanMessage(content=user_prompt)],
            "doc_id": doc_id or "",
            "work_id": work_id or "",
            "elem_id": elem_id or "",
            "selected_entity": selected_entity or {},
            "active_payloads": []
        }
        
        # Array to store the agent's internal progress traces
        execution_progress_logs = []
        final_answer_text = "The agent network failed to compute an operation response."
        
        # Synchronously invoke the graph state machine stream to collect all steps
        for event in graph.stream(initial_state, stream_mode="updates"):
            for node_name, state_update in event.items():
                # Extract the latest text token or log message generated by the active node
                node_content = ""
                if "messages" in state_update and state_update["messages"]:
                    node_content = state_update["messages"][-1].content
                
                # Format a user-friendly progress tracking line mimicking the CLI trace
                if node_name == "agent":
                    log_entry = f"⦾ [AI Reasoning & Optimization Core] -> Deciding next CAD operation..."
                else:
                    log_entry = f"⦾ [{node_name.replace('_', ' ').title()}] -> Action trace processed safely."
                    
                execution_progress_logs.append(log_entry)
                
                # If the node appended text content, store it as the latest reply state
                if node_content:
                    final_answer_text = node_content

        # 💥 FORMULATE THE COMPREHENSIVE DISPLAY MARKDOWN
        # Combine the progress list and the final response into a single scannable message block
        progress_header = "### 🚀 Agent Execution Progress\n" + "\n".join([f"* {log}" for log in execution_progress_logs])
        combined_markdown_reply = f"{progress_header}\n\n---\n\n### 📦 Final Model Response\n{final_answer_text}"

        return JsonResponse({
            'status': 'success',
            'reply': combined_markdown_reply
        })

    except Exception as e:
        print(f"[ERROR IN API CHAT]: {str(e)}")
        return JsonResponse({'status': 'error', 'message': str(e)}, status=500)